system:
    default:
        fielddefinition_settings_templates:
            - { template: "@EzSystemsEzPlatformQueryFieldType/fieldtype/fielddefinition_settings.html.twig" }
        fielddefinition_edit_templates:
            - { template: "@EzSystemsEzPlatformQueryFieldType/fieldtype/fielddefinition_edit.html.twig" }
        field_templates:
            - { template: "@EzSystemsEzPlatformQueryFieldType/fieldtype/field_view.html.twig" }
