services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Ibexa\FieldTypeQuery\FieldType\Query\Type:
        parent: ezpublish.fieldType
        public: true
        autowire: true
        autoconfigure: false
        tags:
            - { name: ezplatform.field_type, alias: '%ezcontentquery_identifier%' }
        arguments:
            $queryTypeRegistry: '@ezpublish.query_type.registry'
            $identifier: '%ezcontentquery_identifier%'

    Ibexa\FieldTypeQuery\FieldType\Mapper\QueryFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: '%ezcontentquery_identifier%' }
        arguments:
            $contentTypeService: '@ezpublish.api.service.content_type'

    Ibexa\FieldTypeQuery\FieldType\Form\QueryFieldFormType: ~

    Ibexa\FieldTypeQuery\Persistence\Legacy\Content\FieldValue\Converter\QueryConverter:
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: '%ezcontentquery_identifier%' }

    ezplatform.query_field_type.not_indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - { name: ezplatform.field_type.indexable, alias: '%ezcontentquery_identifier%' }

    Ibexa\FieldTypeQuery\ContentView\FieldDefinitionIdentifierMatcher:
        tags:
            - { name: ezplatform.view.matcher }
        calls:
            - [setRepository, ['@ezpublish.api.repository']]

    Ibexa\FieldTypeQuery\ContentView\QueryResultsInjector:
        arguments:
            $views: { field: '%ezcontentquery_field_view%', item: '%ezcontentquery_item_view%' }
        tags:
            - { name: kernel.event_subscriber }
